services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apps_moviles
    volumes:
      - ./data:/var/lib/postgresql/data
